import argparse
import csv
import html
import math
from pathlib import Path
from typing import Callable, Dict, List

ROOT_DIR = Path(__file__).resolve().parents[1]

ALGORITHM_COLORS = {
    "bfs": "#d94848",
    "dfs": "#737373",
    "greedy": "#2f9e44",
    "astar": "#1c7ed6",
}

METRICS = [
    {
        "field": "expanded_nodes",
        "filename": "expanded_nodes.svg",
        "title": "Expanded Nodes by Algorithm",
        "subtitle": "Log scale, lower is better",
        "scale": "log",
        "formatter": lambda value: f"{int(value):,}",
    },
    {
        "field": "time_sec",
        "filename": "processing_time.svg",
        "title": "Processing Time by Algorithm",
        "subtitle": "Log scale, lower is better",
        "scale": "log",
        "formatter": lambda value: f"{value:.4f}s",
    },
    {
        "field": "cost",
        "filename": "solution_cost.svg",
        "title": "Solution Cost by Algorithm",
        "subtitle": "Linear scale, lower is better",
        "scale": "linear",
        "formatter": lambda value: f"{int(value)}",
    },
]


def load_successful_rows(input_path: Path) -> List[Dict[str, str]]:
    with input_path.open(newline="", encoding="utf-8") as file:
        rows = list(csv.DictReader(file))
    return [row for row in rows if row["status"] == "success"]


def parse_metric(row: Dict[str, str], field: str) -> float:
    value = row.get(field, "")
    if value == "":
        return 0
    return float(value)


def scale_value(value: float, scale: str) -> float:
    if scale == "log":
        return math.log10(value + 1)
    return value


def row_label(row: Dict[str, str]) -> str:
    level = Path(row["level"]).stem
    heuristic = row["heuristic"]
    if heuristic == "N/A":
        return f"{level} | {row['algorithm']}"
    short_heuristic = heuristic.replace("_target", "").replace("_distance", "")
    return f"{level} | {row['algorithm']} | {short_heuristic}"


def svg_text(x: int, y: int, text: str, size: int = 13, weight: str = "400", fill: str = "#202124") -> str:
    return (
        f'<text x="{x}" y="{y}" font-family="Arial, sans-serif" '
        f'font-size="{size}" font-weight="{weight}" fill="{fill}">'
        f"{html.escape(text)}</text>"
    )


def render_horizontal_bar_chart(
    rows: List[Dict[str, str]],
    field: str,
    title: str,
    subtitle: str,
    scale: str,
    formatter: Callable[[float], str],
) -> str:
    width = 1100
    label_width = 315
    chart_width = 640
    top = 88
    row_height = 34
    bottom = 42
    height = top + row_height * len(rows) + bottom

    values = [parse_metric(row, field) for row in rows]
    scaled_values = [scale_value(value, scale) for value in values]
    max_scaled = max(scaled_values) if scaled_values else 1
    if max_scaled <= 0:
        max_scaled = 1

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#ffffff"/>',
        svg_text(32, 38, title, 22, "700"),
        svg_text(32, 62, subtitle, 13, "400", "#5f6368"),
    ]

    axis_x = label_width
    axis_y = top - 16
    parts.append(f'<line x1="{axis_x}" y1="{axis_y}" x2="{axis_x + chart_width}" y2="{axis_y}" stroke="#d9dce1"/>')

    for index, row in enumerate(rows):
        y = top + index * row_height
        value = values[index]
        scaled = scaled_values[index]
        bar_width = int((scaled / max_scaled) * chart_width)
        color = ALGORITHM_COLORS.get(row["algorithm"], "#495057")

        parts.append(svg_text(32, y + 18, row_label(row), 12))
        parts.append(
            f'<rect x="{axis_x}" y="{y}" width="{bar_width}" height="20" '
            f'rx="3" fill="{color}"/>'
        )
        parts.append(svg_text(axis_x + bar_width + 10, y + 16, formatter(value), 12, "600"))

    parts.append("</svg>")
    return "\n".join(parts)


def write_plots(rows: List[Dict[str, str]], output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    for metric in METRICS:
        svg = render_horizontal_bar_chart(
            rows,
            metric["field"],
            metric["title"],
            metric["subtitle"],
            metric["scale"],
            metric["formatter"],
        )
        output_path = output_dir / metric["filename"]
        output_path.write_text(svg, encoding="utf-8")
        print(f"Saved {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate SVG benchmark plots")
    parser.add_argument(
        "--input",
        default="results/benchmark_results.csv",
        help="Benchmark CSV generated by scripts/run_benchmarks.py",
    )
    parser.add_argument(
        "--output-dir",
        default="results/plots",
        help="Directory where SVG plots will be written",
    )
    args = parser.parse_args()

    rows = load_successful_rows(ROOT_DIR / args.input)
    write_plots(rows, ROOT_DIR / args.output_dir)


if __name__ == "__main__":
    main()
